version: '2'

services:
  spark:
    image: s1mplecc/spark-hadoop:3
    hostname: master
    environment:
      - SPARK_MODE=master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ~/docker/spark/share:/opt/share
    ports:
      - '8080:8080'
      - '4040:4040'
      - '8088:8088'
      - '8042:8042'
      - '9870:9870'
      - '19888:19888'
  spark-worker-1:
    image: s1mplecc/spark-hadoop:3
    hostname: worker1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://master:7077
      - SPARK_WORKER_MEMORY=512m
      - SPARK_WORKER_CORES=1
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
    volumes:
      - ~/docker/spark/share:/opt/share
    ports:
      - '8081:8081'
  spark-worker-2:
    image: s1mplecc/spark-hadoop:3
    hostname: worker2
    environment:
      - spark_mode=worker
      - spark_master_url=spark://master:7077
      - spark_worker_memory=512m
      - spark_worker_cores=1
      - spark_rpc_authentication_enabled=no
      - spark_rpc_encryption_enabled=no
      - spark_local_storage_encryption_enabled=no
      - spark_ssl_enabled=no
    volumes:
      - ~/docker/spark/share:/opt/share
    ports:
      - '8082:8081'
  spark-client:
    build: .
    hostname: client
    environment:
      - spark_mode=worker
      - spark_master_url=spark://master:7077
      - spark_worker_memory=512m
      - spark_worker_cores=1
      - spark_rpc_authentication_enabled=no
      - spark_rpc_encryption_enabled=no
      - spark_local_storage_encryption_enabled=no
      - spark_ssl_enabled=no
    volumes:
      - ~/docker/spark/share:/opt/share
      - type: bind
        source: ./data_processing.py
        target: /opt/data_processing.py
      - type: bind
        source: ./run.sh
        target: /opt/run.sh
    ports:
      - '8083:8081'
